version: "3.7"

services:
  revcord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./revcord.sqlite:/app/revcord.sqlite:rw
      - ./.env:/app/.env
    restart: unless-stopped
